#!/bin/bash
# OSS跨域配置指导脚本

echo "=== OSS跨域访问配置指导 ==="
echo ""
echo "问题说明："
echo "OSS存储桶未配置跨域访问规则，导致浏览器阻止图片加载"
echo ""
echo "配置步骤："
echo "1. 登录阿里云OSS控制台：https://oss.console.aliyun.com/"
echo "2. 选择存储桶：nanyiqiutang"
echo "3. 配置跨域设置：权限管理 > 跨域设置"
echo "4. 创建跨域规则，配置如下："
echo ""
echo "   来源 (AllowedOrigin): *"
echo "   允许Methods: GET, POST, PUT, DELETE, HEAD"
echo "   允许Headers: *"
echo "   暴露Headers: ETag, x-oss-request-id"
echo "   缓存时间: 3600"
echo ""
echo "5. 保存配置"
echo ""
echo "配置完成后测试："
echo "  ./test-oss-access.sh"
echo "  ./switch-image-source.sh oss"
echo ""
echo "当前状态：使用本地图片源，图片加载正常" 